# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ismael-hubuc"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "hubuc.tfstate"
    region         = "us-east-1"
  }
}
